#!/usr/bin/python
import MySQLdb
import ftplib
import smtplib

from email.mime.text import MIMEText

db = MySQLdb.connect(host="10.0.0.105",    # your host, usually localhost
                     user="weewx",         # your username
                     passwd="weewx123!",  # your password
                     db="weewx")        # name of the data base

# you must create a Cursor object. It will let
#  you execute all the queries you need
cur = db.cursor()

# Use all the SQL you like
cur.execute("select dateTime, outTemp from archive order by dateTime desc limit 1")

# print all the first cell of all the rows
for row in cur.fetchall():
    outTemp = row[1]

db.close()

# me == the sender's email address
# you == the recipient's email address
msg['Subject'] = 'The contents of %s' % textfile
msg['From'] = brian.oickle@gmail.com
msg['To'] = brian.oickle@gmail.com

# Send the message via our own SMTP server, but don't include the
# envelope header.
s = smtplib.SMTP('localhost')
s.sendmail(me, [you], outTemp.as_string())
s.quit()
